<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\WowProxy.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WowProxy.Core.Abstractions\WowProxy.Core.Abstractions.csproj" />
    <ProjectReference Include="..\WowProxy.Core.SingBox\WowProxy.Core.SingBox.csproj" />
    <ProjectReference Include="..\WowProxy.Domain\WowProxy.Domain.csproj" />
    <ProjectReference Include="..\WowProxy.Infrastructure\WowProxy.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

</Project>
